#ifndef  STP_CONFIG_H
#define  STP_CONFIG_H


#define STP_SERIAL_DATA     MGPIOA_PORT,MGPIO_PIN0
#define STP_STOR_DATA       MGPIOA_PORT,MGPIO_PIN1
#define STP_SHIFT_DATA      MGPIOA_PORT,MGPIO_PIN2

#define STP_SERIAL_DATA_1     MGPIOA_PORT,MGPIO_PIN3
#define STP_STOR_DATA_1      MGPIOA_PORT,MGPIO_PIN4
#define STP_SHIFT_DATA_1     MGPIOA_PORT,MGPIO_PIN5



#endif
